---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:5.0.0
    depends_on:
      - zookeeper
    networks:
      - kafka-network
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  postgres:
    image: hepsiburada/postgres:13.1-case
    ports:
      - "5432:5432"
    environment:
      - PGDATA=postgres

  init:
    image: docker.io/onurozerdal/hepsiburada-init:latest
    build: .
  view-producer:
    image: docker.io/onurozerdal/hepsiburada-view-producer:latest
    build: .
  stream-reader:
    image: docker.io/onurozerdal/hepsiburada-stream-reader:latest
    build: .
  etl-process:
    image: docker.io/onurozerdal/hepsiburada-etl-process:latest
    build: .
  api:
    image: docker.io/onurozerdal/hepsiburada-api:latest
    build: .
networks:
  kafka-network:
    name: kafka-network
